local table = {
"you have been skibidied by the rizzler"
"MUAHAHAHHAHAHAHHAHAHAHHAHAHAHH😈😈😈😈😈😈😈😈😈"
}

while true do task.wait(.25)
print("hai")
local part1 = Instance.New("Part")
part1.Anchored = false
print("hai2")
task.wait(0.1)
print("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")
local Hint = Instance.New("Hint",game.Workspace)
while wait(1) do
local value = math.random(1, #table)
local text = table[value]
Hint.Text = text
end
