while true do task.wait(.25)
print("hai")
local part1 = Instance.New("Part")
part1.Anchored = false
print("hai2")
task.wait(0.1)
print("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")
local Hint = Instance.New("Hint",game.Workspace)
task.wait(0.1)
Hint.Text = "you have been skibidied by the rizzler"
task.wait(0.1)
Hint.Text = "MUAHAHAHHAHAHAHHAHAHAHHAHAHAHH👿👿👿👿👿👿👿👿👿"
end
